package com.devikapps.vaikaparts;

import static java.lang.annotation.ElementType.*;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * Marker annotation indicating that the annotated element (class, method, or constructor) was
 * automatically generated by the AR Infrastructure Generator (`ar-infra-cli`).
 *
 * <p>All classes annotated with {@code @InfraGenerated} are part of the production-ready
 * infrastructure template. Developers should treat them as generated infrastructure code, not
 * handwritten business logic.
 *
 * <p>This annotation embeds default metadata (signature, version, generation timestamp) so that
 * tools and runtime scanners can verify that the class belongs to the generated infrastructure.
 *
 * <p>Retention: {@link java.lang.annotation.RetentionPolicy#RUNTIME} so that frameworks or runtime
 * scanners can detect and process generated infrastructure elements.
 */
@Documented
@Retention(RUNTIME)
@Target({TYPE, METHOD, CONSTRUCTOR})
public @interface InfraGenerated {
  /** * Unique signature identifying the generator. * Default: "ar-infra-cli" */
  String signature() default "ar-infra-cli:2135f31944e972db";

  /** * Version of the infrastructure generator used. * Default: "1.0.0" */
  String version() default "0.2.0";

  /** * Timestamp or build identifier when generation occurred. * Default: "" */
  String generatedAt() default "2026-03-13T14:10:14.409702+00:00";
}
